1601057700845	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1601066065356	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1601066065356	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1601066065360	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1601066065361	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1601066068613	Sync.Service	DEBUG	User-Agent: Firefox/81.0 (Linux x86_64) FxSync/1.83.0.20200921095100.desktop
1601066068613	Sync.Service	INFO	Starting sync at 2020-09-25 16:34:28 in browser session C6DT90llQije
1601066068613	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1601066068615	Sync.Status	INFO	Resetting Status.
1601066068616	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1601066068616	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1601066068616	FirefoxAccounts	DEBUG	getOAuthToken enter
1601066068617	FirefoxAccounts	TRACE	getCachedToken returning cached token
1601066068617	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1601066068617	Sync.BrowserIDManager	INFO	Getting keys
1601066068617	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1601066068618	Sync.BrowserIDManager	INFO	Getting an assertion from: https://token.services.mozilla.com/1.0/sync/1.5
1601066068618	Sync.BrowserIDManager	DEBUG	Getting a token using OAuth
1601066068618	FirefoxAccounts	DEBUG	getAccessToken enter
1601066068618	FirefoxAccounts	DEBUG	getOAuthToken enter
1601066068618	FirefoxAccounts	TRACE	getCachedToken returning cached token
1601066068618	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1601066068619	FirefoxAccounts	DEBUG	Using cached scopedKeys data for https://identity.mozilla.com/apps/oldsync
1601066068619	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1601066068619	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1601066068622	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1601066068622	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1601066068623	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1601066068624	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: TypeError: err.response is undefined(resource://services-sync/browserid_identity.js:508:13) JS Stack trace: _fetchTokenUsingOAuth/<@browserid_identity.js:508:13
1601066068624	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1601066068624	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1601066068625	Sync.BrowserIDManager	ERROR	Failed to fetch a token for authentication: TypeError: err.response is undefined(resource://services-sync/browserid_identity.js:508:13) JS Stack trace: _fetchTokenUsingOAuth/<@browserid_identity.js:508:13
1601066068627	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1601066068630	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for undefined
1601066068632	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/164549947/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1601066068633	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1601066068633	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1601066068633	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1601066068634	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1601066068635	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1601066068644	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
